# Generated by Django 2.0.6 on 2018-06-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfdata',
            name='t_id',
            field=models.IntegerField(),
        ),
    ]
